const artists = [
  "Alba August",
  "Amena Alsameai",
  "Daniel Adams-Ray",
  "Elliphant",
  "Eric Saade",
  "Erik Lundin",
  "Jacqline",
  "Jacco",
  "Janice",
  "Jocke Åhlund",
  "Kalam Podcast",
  "Kurt.",
  "Marcus Price och Carli",
  "Marit Bergman",
  "Afasi",
  "Medina",
  "Michel Dida",
  "Miriam Bryant",
  "Nicole Sabouné",
  "Petter ft. Dj Sleepy & Eye N' I",
  "Silvana Imam",
  "Singers In Solidarity with Palestine",
  "Siw Malmkvist",
  "SUNNAN",
  "Stefan Sundström",
  "Steph K",
  "Stor",
  "Titiyo",
  "Thomas Stenström",
];

export default artists;
